### ISSUE TITLE
Allow to print unicode character

### ISSUE THREAD

**Issue by xXKeyleXx** [patou/gitmoji-intellij-plugin#1]
Could you add an option to switch to the unicode character instead of the `:emoji:` style?
This would be really helpfull when you don't use github as your VCS provider but you still want to use  gitmojis.

Thanks!

**Comment by patou** [comment]
Thanks for yours interest @xXKeyleXx 
I will look at how to do this.

**Comment by patou** [comment]
Hello @xXKeyleXx, I added an option to allow to print unicode character, it's what you want ?
You can also add review on the plugin page :  https://plugins.jetbrains.com/plugin/12383-gitmoji/
Thanks

**Comment by xXKeyleXx** [comment]
That's exactly what I wanted! Thank you!

**Comment by felixranesberger** [comment]
+1 Thanks for your work! 🎉
