### ISSUE TITLE
Auto Search Feature Missing in Commit Dialog?

### ISSUE THREAD

**Issue by akibarika** [patou/gitmoji-intellij-plugin#101]
Previously, I remember that I could type a keyword in the commit dialog to filter `Gitmoji`. This auto-search functionality seems to have disappeared. Is there a setting I missed, or could this be a configuration issue?

For example, you can filter bug in this case 

![CleanShot 2024-11-08 at 11 30 19](https://github.com/user-attachments/assets/cfee2ad8-6078-4d6c-8142-a09176f760ba)

### Environment:

WebStorm Version: 2024.2.4
Gitmoji Plugin Version: 2.2.2
OS: MacOS 14.6.1

**Comment by patou** [comment]
Hello,

I have not this problems, did you try to type some key ? The filter will be appearing : 
![image](https://github.com/user-attachments/assets/c1afefd7-e24e-4e38-877a-e55c4ac03f8c)

**Comment by akibarika** [comment]
Hi @patou 

Thanks for your message, I have fixed the issue by switching non-modal commit interface. Now I can search and filter the Gitmoji.

![CleanShot 2024-12-05 at 11 51 44](https://github.com/user-attachments/assets/c7096ff5-b299-43db-896d-d252f7ff8bd8)
