### ISSUE TITLE
I can't see the icon in the android studio git viewer

### ISSUE THREAD

**Issue by dbordera** [patou/gitmoji-intellij-plugin#105]
I have the latest version of android studio, the: Android Studio Ladybug | 2024.2.1 Patch 3 from November 22, 2024. On the other hand in github desktop for example if I see it, but on the other hand in android studio.

**Comment by dbordera** [comment]
Github desktop... OK
![image](https://github.com/user-attachments/assets/b04b767c-c610-40d9-9b9e-8eabd42294f0)

Android Studio
![image](https://github.com/user-attachments/assets/f6ec6d27-d9ff-47c2-be01-017f50698985)

**Comment by patou** [comment]
> Github desktop... OK ![image](https://private-user-images.githubusercontent.com/101561462/391997175-b04b767c-c610-40d9-9b9e-8eabd42294f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzUzNjgsIm5iZiI6MTczMzIzNTA2OCwicGF0aCI6Ii8xMDE1NjE0NjIvMzkxOTk3MTc1LWIwNGI3NjdjLWM2MTAtNDBkOS05YjllLThlYWJkNDIyOTRmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxNDExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGQ3ZDI5MTg4NGEwNjNlM2U5ZDQ2Y2U2ZWM3ZWU5MzY2MGRlZWYyNjYzMTRhZDcyNDFlZjViNmE0ZDc0MWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PC8LHSPkDx3TjLAYuGc0muu2dw5Ha4BITp1L9WZje7Y)
> 
> Android Studio ![image](https://private-user-images.githubusercontent.com/101561462/391996883-f6ec6d27-d9ff-47c2-be01-017f50698985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzUzNjgsIm5iZiI6MTczMzIzNTA2OCwicGF0aCI6Ii8xMDE1NjE0NjIvMzkxOTk2ODgzLWY2ZWM2ZDI3LWQ5ZmYtNDdjMi1iZTAxLTAxN2Y1MDY5ODk4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxNDExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODBiYWRhNmZmZTBjN2ZlNDhjMWM3NjNhNDAwMmI0ZTU1YzNlNWM4ZDI5MDcxZGI2MDdhNmY2MTRiMTVhY2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.paZ3jfjh69Z0_3GLJt-UqP_0-EapOaNvluK1Sph2VLc)

IntelliJ didn't replace the emoji code to emoji. There is an issue for this : https://youtrack.jetbrains.com/issue/IJPL-90283

This extension allow adding a new column in the git log with the emoji icon : 
![Git column](https://github.com/patou/gitmoji-intellij-plugin/raw/master/screenshot/gitmoji-column.png)

You can add this column by click on the 👁️  icon : 
![image](https://github.com/user-attachments/assets/158c1dde-d657-43f9-9968-a0a03aff61db)

**Comment by dbordera** [comment]
Thank you! I got it!
