### ISSUE TITLE
It's strange that i lose all of commit emoji info...Please help

### ISSUE THREAD

**Issue by arvinxx** [patou/gitmoji-intellij-plugin#15]
At first thank you for this great plugin. I love it very much.

It works well before.But it seems don't work right now like below.

![image](https://user-images.githubusercontent.com/28616219/104090484-18489b80-52b2-11eb-8a51-483cf0110061.png)

 My webstorm version is 2020.3.1 & gitmoji plugin is 1.6.0.

What happen? please help, thanks a lot.

---
update

it seems there be some error 

```
java.lang.NoClassDefFoundError: Could not initialize class kotlin.internal.PlatformImplementationsKt
	at kotlin.ExceptionsKt__ExceptionsKt.addSuppressed(Exceptions.kt:71)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:531)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I have tried restart, reinstall but all failed.

**Comment by patou** [comment]
It's just after update your webstorm version or gitmoji plugin ?

Do you have other plugins that don't work?

**Comment by arvinxx** [comment]
> It's just after update your webstorm version or gitmoji plugin ?
> 
> Do you have other plugins that don't work?

No,it just the gitmoji plus plugin.
But it's strange that after I delete all cache of Webstorm. It can work well...
So I close it.Thanks for replying.😄

**Comment by patou** [comment]
@arvinxx It's a good news that works agains.
thanks

**Comment by gclm** [comment]
I also encountered the same problem

**Comment by gclm** [comment]
My idea  2020.3.2 version is  & gitmoji plugin is 1.70.
