### ISSUE TITLE
Icons are not visible on Webstorm (Windows)

### ISSUE THREAD

**Issue by pookdeveloper** [patou/gitmoji-intellij-plugin#17]
Hi i dont see the icons in windows with webstorm

![image](https://user-images.githubusercontent.com/3384734/105004845-cc75bf00-5a34-11eb-8290-35c28b3cf8b5.png)

Thanks

**Comment by patou** [comment]
Hello,

It's very strange, It's display emoji.

What is the version of windows ?

**Comment by pookdeveloper** [comment]
@patou 
![image](https://user-images.githubusercontent.com/3384734/105024497-757be400-5a4c-11eb-98a6-6c04e11c01f2.png)

**Comment by patou** [comment]
I think you havn't the emoji font installed on your computer.

On this website https://getemoji.com/  did you display emoji ?

**Comment by pookdeveloper** [comment]
Yes I can seethe emoji, and I can use in VSCode an in Windows
![image](https://user-images.githubusercontent.com/3384734/105026610-05229200-5a4f-11eb-933d-f03a49eebe3b.png)
![image](https://user-images.githubusercontent.com/3384734/105026633-0b187300-5a4f-11eb-9aed-1a5a6beb42e6.png)

**Comment by patou** [comment]
I reproduce the problem on my windows computer after update to 2020.3

**Comment by rubenvitt** [comment]
same issue on Mac v2020.3. 🐛
The icons are being displayed correctly in the commitBox.

![Screenshot 2021-01-20 at 07 41 54](https://user-images.githubusercontent.com/19268519/105137063-060cff80-5af3-11eb-9552-949df3845c8f.png)

**Comment by pookdeveloper** [comment]
doesn't work for me in the box Thanks

**Comment by rubenvitt** [comment]
This IntelliJ-versions seems to be inconsistent. Emojis also don't work for me in the push-window & git history.

![Uploading Screenshot 2021-01-20 at 08.14.50.png…]()

**Comment by patou** [comment]
@rubenvitt You have the same issues on Mac ?
On my Mac, with IntelliJ 2020.3, icons display well.

**Comment by rubenvitt** [comment]
IntelliJ IDEA 2020.3.2 RC (Ultimate Edition)
Build #IU-203.7148.40, built on January 19, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7

**Comment by patou** [comment]
I don't found a issues on IntelliJ about this, but emoji didn't works on popup chooser.
If you look on the history commit message list, emoji not displayed.
But when you select it it's displayed in the text area.

**Comment by patou** [comment]
On my Mac :
<img width="346" alt="Capture d’écran 2021-01-20 à 12 35 46" src="https://user-images.githubusercontent.com/841858/105169649-1b4a5400-5b1c-11eb-96b3-2b7ad583a4ec.png">

IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Licensed to Patrice DE SAINT STEBAN
You have a perpetual fallback license for this version.
Subscription is active until December 5, 2021.
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: eslint.additional.file.extensions=svelte
Non-Bundled Plugins: com.github.patou.gitmoji, org.intellij.plugins.hcl, branchmanager, org.nik.presentation-assistant, training, com.intellij.kubernetes, String Manipulation, com.jetbrains.codeWithMe, com.redhat.devtools.intellij.quarkus, com.dmarcotte.handlebars, dev.blachut.svelte.lang, org.jetbrains.kotlin, zielu.gittoolbox, com.google.gct.core, Pythonid

**Comment by patou** [comment]
I will revert by using image instead of emoji.
(I remove image to allow to update the list of gitmoji without to create a new version for adding image, and reduce size of plugins, and allow in futur to add custom emoji).

**Comment by patou** [comment]
I'm created an issues on IntelliJ : https://youtrack.jetbrains.com/issue/IDEA-259895

**Comment by patou** [comment]
I add an option for display icon instead of emoji.
This option is by default on windows.

**Comment by patou** [comment]
@pookdeveloper The bug will be correct in the next version in validating by Jetbrains.

You can also add review on the plugin page : https://plugins.jetbrains.com/plugin/12383-gitmoji/
