### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by SturmB** [patou/gitmoji-intellij-plugin#26]
An error message appears when attempting to install this on IntelliJ IDEA 2021.3 (Community Edition), Build #IC-213.5744.223 on Windows 11:

![image](https://user-images.githubusercontent.com/6216224/147674667-5d2252f3-9636-4cda-98c6-da7d102dfaa7.png)

No way to determine why or what to do to get it installed, just a big ol' "NOPE."

**Comment by Jungzl** [comment]
I met the same error above, so I install this plugin from disk, and met a new error ![image](https://user-images.githubusercontent.com/35426360/147714201-f05d43a0-0500-440d-b447-9db876c1d254.png)

**Comment by patou** [comment]
Thanks for the report. It's with the new version 1.9 and intellij 2021.3 ?

**Comment by patou** [comment]
@SturmB and @Jungzl what OS do you use ?

**Comment by Jungzl** [comment]
> @SturmB and @Jungzl what OS do you use ?

Yes, and OS is Windows10 pro 21H2

**Comment by SturmB** [comment]
> @SturmB and @Jungzl what OS do you use ?

Yes, it is with v1.9.0 of the plugin and now IntelliJ IDEA 2021.3.1 (Community Edition), Build #IC-213.6461.79. (I updated it yesterday after I posted about this problem.)

Actually, here's the output of its About dialog:

> IntelliJ IDEA 2021.3.1 (Community Edition)
> Build #IC-213.6461.79, built on December 28, 2021
> Runtime version: 11.0.13+7-b1751.21 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Windows 11 10.0
> GC: G1 Young Generation, G1 Old Generation
> Memory: 2024M
> Cores: 6
> Non-Bundled Plugins:
>     idea.plugin.protoeditor (213.6461.28)
>     org.jetbrains.kotlin (213-1.6.10-release-923-IJ5744.223)
> 
> Kotlin: 213-1.6.10-release-923-IJ5744.223

And here's the output of Windows' About dialog:

> Edition	Windows 11 Pro
> Version	21H2
> Installed on	‎12/‎16/‎2021
> OS build	22000.376
> Experience	Windows Feature Experience Pack 1000.22000.376.0

**Comment by patou** [comment]
A new version is under validation and will correct this installation problem. 
Sorry for the inconvenience.

Do not hesitate to put a review on the plugin page :
https://plugins.jetbrains.com/plugin/12383-gitmoji-plus-commit-button/reviews

**Comment by Jungzl** [comment]
![image](https://user-images.githubusercontent.com/35426360/147822226-edef128d-b706-4a1f-9d0d-e81a4d3d7e46.png)
🎉🎉🎉Thank you so much!

**Comment by SturmB** [comment]
I can confirm that v1.9.1 fixes the issue. Thank you, @patou!
