### ISSUE TITLE
Can all content be completed automatically? 

### ISSUE THREAD

**Issue by 721806280** [patou/gitmoji-intellij-plugin#27]
Only auto-fill after the current selection `:bug:`

Expect all content to be filled in automatically. For example`:bug: fix a bug. ` 

If it is a new feature and is planned to be implemented, it would be better to have a separate configuration;

**Comment by patou** [comment]
Thanks for this feature request. I'm not implementing this feature because I havn't the need to have the description of the gitmoji .

But if it's a need for you, it's possible to add an option for this.

**Comment by 721806280** [comment]
Thank you very much for your reply. If feasible, please update this feature as soon as possible and look forward to the next version.

**Comment by patou** [comment]
Thanks for your report. I not planning to work on this feature soon, but feel free to propose a pull request, I will review it with pleasure.

**Comment by 721806280** [comment]
> Thanks for your report. I not planning to work on this feature soon, but feel free to propose a pull request, I will review it with pleasure.

Approximately how long does this function have to wait?

**Comment by patou** [comment]
This new option will be in the next version.

**Comment by huyz** [comment]
I may be misunderstanding here but it sounded like OP wanted to _autocomplete_ on the gitmoji description, but the PR sounds like it's _inserting_ the gitmoji description (which doesn't sound very useful to me, as emojis are supposed to be short-hand and including generic descriptions would defeat the purpose).  Am I mistaken?

**Comment by patou** [comment]
> I may be misunderstanding here but it sounded like OP wanted to _autocomplete_ on the gitmoji description, but the PR sounds like it's _inserting_ the gitmoji description (which doesn't sound very useful to me, as emojis are supposed to be short-hand and including generic descriptions would defeat the purpose). Am I mistaken?

It's allready have filter on the gitmoji description :
![image](https://user-images.githubusercontent.com/841858/180991810-f88aed99-50a3-4735-86b8-bf97625b0d75.png)

Maibe I don't understand this issues, but @721806280 ask an option to insert all the gitmoji description like : 
`:bug: fix a bug.`

**Comment by huyz** [comment]
My bad, I misunderstood them. Ignore me :)
