### ISSUE TITLE
Hangs agian in settings

### ISSUE THREAD

**Issue by Jungzl** [patou/gitmoji-intellij-plugin#29]
![image](https://user-images.githubusercontent.com/35426360/163077063-733332b5-5c80-4bd8-9280-0c170fb656e7.png)

IDE: WebStorm 2022.1
OS: Windows 10 pro 21H2

**Comment by asimuleo** [comment]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/74406312/163100387-168f8f31-0355-4582-bb28-991dc6e40174.png">

**Comment by patou** [comment]
Hello which version of the Gitmoji plugin are you using for ?
This bug has been normaly corrected in version 1.9.

**Comment by Jungzl** [comment]
Here is only v1.8.1 
![image](https://user-images.githubusercontent.com/35426360/163557993-91ea3f26-d94f-4295-8fcd-5e5d3f1498c3.png)

**Comment by Jungzl** [comment]
Then I import the zip file downloaded from [here](https://plugins.jetbrains.com/plugin/12383-gitmoji-plus-commit-button/versions/stable), but IDEA shows
![image](https://user-images.githubusercontent.com/35426360/163558255-764aa8e2-b8bb-4e6c-a063-57023bcf0683.png)

**Comment by flex-seongbok** [comment]
GitmojiPlus 1.9.0 and 1.9.1 are not compatible with IntelliJ 2022.1

Thank you for develop such great plugin

<img width="989" alt="스크린샷 2022-04-15 오후 8 08 11" src="https://user-images.githubusercontent.com/96708645/163564087-0c55c288-57cd-4f65-a765-2170ad3f3495.png">

**Comment by patou** [comment]
Ok thanks, I will look why it's not compatible !
