### ISSUE TITLE
[Feature] auto-completion

### ISSUE THREAD

**Issue by GMartigny** [patou/gitmoji-intellij-plugin#3]
Hi,
It would be nice to have auto-completion in the commit dialog. I have no idea is this is possible or how it would be done. You can look at what is done by https://github.com/biezhi/gitmoji-plugin.
Thanks for the plugin anyway

**Comment by patou** [comment]
I fork the project from biezhi for create this new plugin and change the auto-completion to the current button.
Maybe it's the implementation, but I found that auto-completion was not very relevant.
IntelliJ keeps the last message in the commit window and auto-completion works when a message is empty.

**Comment by GMartigny** [comment]
I certainly don't mind the button way. It's just that it allow me to keep my hands on the keyboard.
Maybe some kind of shortcut could do the same.

**Comment by patou** [comment]
Yes I can look at add a shortcut.

**Comment by GMartigny** [comment]
Close in favor of #5
