### ISSUE TITLE
Released version not available in JetBrains Marketplace

### ISSUE THREAD

**Issue by theMattCode** [patou/gitmoji-intellij-plugin#33]
Tried to update and find the new release 1.10.0 via Marketplace, but it seems not available. Is there any manual step required or did the automatic upload via GitHub workflow fail in https://github.com/patou/gitmoji-intellij-plugin/actions/runs/2192558651?

**Comment by patou** [comment]
Yes there are a manual validation from Jetbrains (normally 2 business days)

**Comment by patou** [comment]
@theMattCode it's has been validated https://plugins.jetbrains.com/plugin/12383-gitmoji-plus-commit-button/versions/stable/169202
