### ISSUE TITLE
Insert nothing after emoji character

### ISSUE THREAD

**Issue by Coniface** [patou/gitmoji-intellij-plugin#34]
Setting the "Character after inserted emoji" to "<nothing>" does not work.
If you reopen the Gitmoji settings, it will be switched to "<space>" so there is always a space added after the Gitmoji by default.

Because of this, as I manually remove the space each time (which is tedious), when I use the extension it adds a new emoji at the beginning of my commit message instead of replacing it with another one.

**Comment by patou** [comment]
The correction will be in the next version

**Comment by Coniface** [comment]
Brilliant, many thanks!

Any idea when this next version will come out?

**Comment by patou** [comment]
> Brilliant, many thanks!
> 
> Any idea when this next version will come out?

I next 2 or 3 days.
There are a manual validation for intellij plugin.

**Comment by Coniface** [comment]
Hi @patou 
Just wondering, it has been 15 days since your fix but I still haven't received an update in my IDE plugin.
Is it stuck on Jetbrains' side or did you maybe forget to publish the fixed version?

Anyway, many thanks for the great plugin and the quick support response! :grin:

**Comment by patou** [comment]
Hi,

Sorry I'm not plublish the new version because I work on a new fonctionnality (you can see the PR) but it's not work and I'm answered help on the jetbrains forum but no responses ...

I will publish without this PR.

**Comment by Coniface** [comment]
Oh ok, I thought you were going to publish a patch version just with this fix and that the new feature would come in yet another version later!

I just came back because I only commit through JetBrains IDE's interface so I experience the bug on a daily basis.

Thank you for your quick reply :tada:

**Comment by patou** [comment]
Sorry for late reaction with holidays.
I publish for validation the version 1.11.0, the version will be available in next few days.

**Comment by Coniface** [comment]
I received the update this morning, the fix works just fine, many thanks for all this! :ok_hand:

**Comment by patou** [comment]
Thanks for the review
