### ISSUE TITLE
Button not usable

### ISSUE THREAD

**Issue by xXKeyleXx** [patou/gitmoji-intellij-plugin#4]
Sometimes the Gitmoji-Button is just a grey square and can't be used. Reopening the commit window fixes this problem most of the time.

![gitmoji](https://user-images.githubusercontent.com/631504/75690356-fc906400-5ca2-11ea-8942-04ebf18ead2b.png)

**Comment by patou** [comment]
I already seen this bug, but I don't know why.
I will look at this problem.

**Comment by xXKeyleXx** [comment]
Mostly it seems to happen when the IDE is under heavy load like indexing 🤔

**Comment by xXKeyleXx** [comment]
Yep definitely something like that. I just noticed, as soon as the indexing (and other background tasks) were done, the buton appeared 🧙

**Comment by patou** [comment]
@xXKeyleXx Yes I noticed this also. But I don't find any information for that.

**Comment by patou** [comment]
I found there are an option to say that the action is dump aware (not dependant to indexing)
