### ISSUE TITLE
Last package versions incompatible with last IDE versions

### ISSUE THREAD

**Issue by mathieutu** [patou/gitmoji-intellij-plugin#42]
Hi, thanks for your great work!
I'm using `2023.1` version, and the only version of this package I can install is the `1.8.1`.
Do you think you could set the version as `xxxx+` like for 1.8.1 instead of defining a range like the last ones?

Thanks!

<img width="578" alt="Screenshot 2023-02-21 at 17 33 20" src="https://user-images.githubusercontent.com/11351322/220404586-bae01f05-e1c5-41da-b22e-d274a7b1d40d.png">

**Comment by patou** [comment]
Merci @mathieutu pour la demande, je viens de faire une nouvelle version qui accepte la prochaine version 2023.1.
Malheureusement, la dernière version de l'IntelliJ Gradle plugin ne permet plus d'avoir une version en mode xxxx+
Le temps de validation du plugin, il sera disponible dans les prochains jours.

**Comment by mathieutu** [comment]
C'est surprenant. Ils attendent donc qu'à chaque nouvelle version, les développeurs mettent à jour leur packages directement ?

**Comment by patou** [comment]
C'est déployé

**Comment by mathieutu** [comment]
@patou Toujours le même problème 😔. À chaque mise à jour de l'IDE je repars sur la 1.8.1 qui est buggée.

**Comment by patou** [comment]
> @patou Toujours le même problème 😔. À chaque mise à jour de l'IDE je repars sur la 1.8.1 qui est buggée.

Je refait une nouvelle version pour la version 2023.2.

Il y a une nouvelle version du template de plugin, je ne sais pas si cela change quelque chose, mais c'est une tache à faire, et j'ai aussi une méthode qui est déprécié sur laquelle il faut que je me penche aussi.

**Comment by patou** [comment]
C'est maintenant disponible !
