### ISSUE TITLE
:adhesive_bandage: does not get displayed as Icon

### ISSUE THREAD

**Issue by D4sK43nguru** [patou/gitmoji-intellij-plugin#47]
When I use the adsehive_bandage gitmoji, in gitlab, gitkraken and the console it still gets displayed as 

> `:adhesive_bandage:`

and not as 

> 🩹

**Comment by patou** [comment]
Hello, the issue isn't with plugin, i think it's because gitlab didn't know this emoji.

You can configure in the plugin to use unicode instead of code.
