### ISSUE TITLE
Custom config about lang

### ISSUE THREAD

**Issue by BTMuli** [patou/gitmoji-intellij-plugin#48]
Chinese is needed!

Please provide a place where can set the language, or customize the text of the hint.

**Comment by patou** [comment]
The data come from the website : https://gitmoji.dev/ 
There are no translation on this website.

**Comment by BTMuli** [comment]
https://github.com/patou/gitmoji-intellij-plugin/blob/master/src/main/resources/gitmojis.json

Is there a way to customize it?

**Comment by patou** [comment]
It's just a fallback if the download from the gitmoji website not works.

**Comment by BTMuli** [comment]
> There are no translation on this website.

Here is a similar plugin in VSCode: [gitmoji-vscode   zh-cn.json](https://github.com/seatonjiang/gitmoji-vscode/blob/main/languages/bundle.l10n.zh-cn.json)

And here is another similar plugin in IDEA: [gitmoji-plus-intellij-plugin zh-CN.json](https://github.com/h3110w0r1d-y/gitmoji-plus-intellij-plugin/blob/main/src/main/resources/gitmojis/zh-CN.json)

Since Gitmoji will not be updated in a large number of short periods of time,it is enough to do localization directly, and the API can be used to detect quantity/content differences.

**Comment by patou** [comment]
The plugin is now translated to chineese.
