### ISSUE TITLE
[feature] Add a shortcut for open the gitmotji list

### ISSUE THREAD

**Issue by patou** [patou/gitmoji-intellij-plugin#5]
As proposed in issue #3 by @GMartigny, it's can be a good thing to add a short cut for open the list of gitmoji

**Comment by patou** [comment]
An idea for the shortcut ?

**Comment by patou** [comment]
I test "Ctrl Alt g" (or "Cmd Alt g" on Mac OS)

**Comment by GMartigny** [comment]
Just an idea (this is going to add a lot of complexity), you should allow user to configure the shortcut.
Someone could already have something bound to `ctrl + alt + g`, or could have a hard time doing it.

**Comment by patou** [comment]
@GMartigny  In IntelliJ Settings there are an option for change all shortcut : 

<img width="1336" alt="Capture d’écran 2020-03-12 à 15 10 33" src="https://user-images.githubusercontent.com/841858/76530198-ad50ed00-6473-11ea-8211-5c61a0c4e009.png">
