### ISSUE TITLE
Can I add custom emoji

### ISSUE THREAD

**Issue by Invoker-liu** [patou/gitmoji-intellij-plugin#6]
you know i prefer 🐞 to replace 🐛 ,can i replace it

**Comment by patou** [comment]
Hello, I prefere to use the same icons than gitmoji website : https://gitmoji.carloscuesta.me/

Maybe, add a configuration to add customs emotji.

**Comment by Invoker-liu** [comment]
> Hello, I prefere to use the same icons than gitmoji website : https://gitmoji.carloscuesta.me/
> 
> Maybe, add a configuration to add customs emotji.

Thank you for your work ,Look forward to updates
