### ISSUE TITLE
Loosen dependency requirement to enable installs with EAP versions

### ISSUE THREAD

**Issue by pboling** [patou/gitmoji-intellij-plugin#62]
Can the top version requirement be loosened, such that we can use it / test it with the EAP releases?  I like using the EAP releases generally but this is a core part of my workflow, and missing it is impactful.

**Comment by patou** [comment]
Version 2.1.0 plublish with support of 242 EAP

**Comment by patou** [comment]
The template intellij for create a plugin can't allow to not set a until version.

The new version with target to 2025.1 is in validation.

**Comment by pboling** [comment]
@patou - I use another gitmoji plugin when I am unable to use this one, and somehow it doesn't need to set an until version.

Plugin: [Open Gitmoji](https://plugins.jetbrains.com/plugin/20029-open-gitmoji)

It uses a blank until version, and this results in it working with all EAP without doing any new release:
https://github.com/texousliu/open-gitmoji/blob/main/gradle.properties#L9-L10
