### ISSUE TITLE
[Feature request] Fetch gitmojis from source at startup

### ISSUE THREAD

**Issue by KaKi87** [patou/gitmoji-intellij-plugin#7]
Hello,

Would it be possible to automatically fetch gitmojis from source at https://github.com/carloscuesta/gitmoji/blob/master/src/data/gitmojis.json when JetBrains IDE starts so there's no need to update the plugin when the emojis list is updated ?

Thanks.

**Comment by patou** [comment]
Hello,

I think about this, but the problem is for icons, for the moment the icons are in images embedded in the project.

I must change to display directly the emotji in the drop down menu.

After that I can load the json file.

**Comment by KaKi87** [comment]
I understand, would it be possible to dynamically download the icons ?
And if not, downloading all icons, unused ones included ? 😅

**Comment by KaKi87** [comment]
Actually, wouldn't the unicode characters be directly transformed into emojis by the IDE itself ?

**Comment by patou** [comment]
@KaKi87 I am successful use the unicode characters instead of icon.
I can now load data from the json.

**Comment by KaKi87** [comment]
Excellent !

**Comment by KaKi87** [comment]
Hi,
Why did you undo the transformation of emoji codes into emojis in favor of a separate emoji column ? That's space lost.
Thanks
