### ISSUE TITLE
Dropdown is empty with message "No matches found" at first use

### ISSUE THREAD

**Issue by nicovong** [patou/gitmoji-intellij-plugin#81]
At first use of Gitmoji in commit section, dropdown is empty with message `No matches found` and then the commit message is deleted.

![Capture d'écran 2024-07-09 171208](https://github.com/patou/gitmoji-intellij-plugin/assets/30236832/5bde4478-d3a2-4718-99d4-aaf247d35bbb)

> PyCharm 2024.1.3 (Professional Edition)
Build #PY-241.17890.14, built on June 4, 2024
Subscription is active until February 16, 2025.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.github.patou.gitmoji (2.0.0)
  commit-message-helper-idea-plugin (1.4.2)
  org.intellij.plugins.hcl (241.17890.8)
  aws.toolkit.core (3.15-241)
  PlantUML integration (7.10.1-IJ2023.2)
  com.intellij.bigdatatools.core (241.17890.1)
  com.intellij.bigdatatools.binary.files (241.14494.158)
  com.intellij.bigdatatools.rfs (241.17890.1)
  com.datadog.intellij (1.4.4)
  zielu.gittoolbox (500.2.10+233)
  aws.toolkit (3.15-241)

**Comment by patou** [comment]
Thanks for reporting, I'm work on it.
