### ISSUE TITLE
2024.3 EAP support

### ISSUE THREAD

**Issue by BTMuli** [patou/gitmoji-intellij-plugin#92]
rt
![image](https://github.com/user-attachments/assets/0252edb2-b7fc-4c23-8b8b-38f953e5b1b0)

**Comment by patou** [comment]
Hello,

Thanks for the issues, I see that I must migrate the plugin to the new version graddle plugin for allow support to the new EAP.
If someone can help me to the migration of the plugin.

**Comment by DeKaN** [comment]
@patou Can I take migration to the new gradle plugin part? Without updating to new IDEA API

**Comment by patou** [comment]
> @patou Can I take migration to the new gradle plugin part? Without updating to new IDEA API

Hello, you can try to check if it's works but I read that I must update the New IDEA API for migrating.

**Comment by patou** [comment]
The plugin now supports the 2024.3 EAP.
